- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nordejs
    ansible.builtin.commond: dnf module disable nodejs -y
    
  - name: disable default nordejs
    ansible.builtin.commond: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs:20
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home : /app
    
  - name: create app dirrectory
    ansible.builtin.file:
    path: /app
    state: dirrectory

  - name: download catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: extract catalogue code
    ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
      