- name: install my sql component
  hosts: mysql
  become: yes
  tasks: 
  - name : install my sql sever
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
    
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: set up root passowrd
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: copy shipping  service
    ansible.builtin.service:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: demon reload
    ansible.builtin.systemd_service:
      daemon_reload: yes
  
  - name: enable and start shipping
    ansible.builtin.service:
       name: shipping
       state: started
       enabled: yes
      